FROM python:alpine
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
EXPOSE 8000
ENTRYPOINT [ "sh","-c", "python manage.py migrate;python manage.py update_db;python manage.py runserver 0.0.0.0:8000;" ]