# Generated by Django 5.2.8 on 2025-11-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0002_place_address_place_phone_place_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.CharField(editable=False, max_length=500, primary_key=True, serialize=False, unique=True),
        ),
    ]
