# Generated by Django 5.2.8 on 2025-11-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0003_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
