# Generated by Django 5.2.8 on 2025-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0004_alter_place_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
