# Generated by Django 5.2.8 on 2025-11-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0005_place_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='style',
            new_name='styles',
        ),
    ]
