# Generated by Django 5.2.8 on 2025-11-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0006_rename_style_place_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='badges',
            field=models.CharField(blank=True, null=True),
        ),
    ]
