# Generated by Django 5.2.8 on 2025-11-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0007_place_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='reviews_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
