# Generated by Django 5.2.8 on 2025-11-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0008_place_image_place_place_type_place_reviews_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('tickets', models.CharField(max_length=100)),
                ('isTrending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocalGuide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.IntegerField(default=0)),
                ('tours', models.IntegerField(default=0)),
                ('image', models.URLField()),
                ('bio', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('specialties', models.CharField(max_length=255)),
            ],
        ),
    ]
