# Generated by Django 5.2.8 on 2025-11-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0009_event_localguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_hidden_gem',
            field=models.BooleanField(default=False),
        ),
    ]
