# Generated by Django 5.2.8 on 2025-11-20 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmio_bkd', '0011_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
